### ISSUE TITLE
When receiving your badge, the text 'congratulation message' appears to be a link

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/badger-xblock#9]
When a student has successfully passed a section with a badge and the user hovers his mouse over the message,it appears to be a link.

url: https://khda.proversity.org

Steps.
1.  Click on the link above. 
2.  Complete a section to achieve your badge.
3.  After you successfully complete the section and received you badge, hover you mouse over the 'Congratulations message'
4.  The pointer becomes a hand, as to select the link

Results:
When the student click on the message, nothing happens. it should open up the badge OR
The message should not be linked.

**Comment by nicovanniekerk** [comment]
@lidijarad can you please have a look at this, quite possible that it is an html or css styling that is needed or missing.

**Comment by lidijarad** [comment]
@nicovanniekerk, I have removed the cursor property from the badger xblock. Here is the commit. Please could you reinstall this on development/staging or production if you want since it is a small css change. 

Here is the commit:
https://github.com/proversity-org/badger-xblock/commit/454d895dcde3fcc44fe852594fd4da91ec356659

**Comment by nicovanniekerk** [comment]
@mariushuman i did the reinstall this on production, please have a look. Thanks guys.

**Comment by lidijarad** [comment]
@nicovanniekerk @mariushuman, I have checked this and the css fix is live on production.
